site_name: Oráculo
pages:
  - Home: home.html
  - Organização:
    - Gerenciamento de Pessoas:
      - Plano de Comunicação: 'comunicacao.md'
      - Quadro de Conhecimentos: 'conhecimentos.md'
      - Quadro de Horários: "horarios.md"
    - Pipeline: 'pipeline.md'
  - Produto:
    - Visão do Produto: 'visao.md'
    - Documento de Arquitetura: 'arquitetura.md'
    - Protótipos:
      - Protótipo de Baixa Fidelidade: 'prototipo.md'
      - Protótipo de Alta Fidelidade: 'prototipo_alta.md'
    - EAP: 'EAP.md'
  - Planos:
    - Gerenciamento de Riscos:
      - Planejamento de Riscos: 'riscos.md'
    - Gerenciamento de Qualidade:
      - Planejamento de Qualidade: "planoQualidade.md"
    - Gerenciamento de Custos:
      - Planejamento de custos: "custos.md"
    - Cronograma: 'diagrama_gantt.md'
  - Sprints:
      - Sprint 1: "sprint1.md"
theme:
  name: material
  language: pt
repo_name: 'Repositório'
repo_url: 'https://github.com/fga-eps-mds/2021-2-Oraculo-Doc'
